pipeline{
    agent any

    tools{
    	maven 'maven 3.6.1'
    }

    stages{
	stage("build"){
		when{
			changeset "**/worker/**"
		}
		steps{
                	echo 'Compiling worker app'
                	dir('worker'){
                 		 sh 'mvn compile'
                	}
		}		 
	}
        stage("test"){
		when{
			changeset "**/worker/**"
		}
            	steps{
	    		echo 'Testing worker app'
                        dir('worker'){
                                 sh 'mvn clean test'
                        }
	    	}  
	}
        stage("package"){
		when{
			changeset "**/worker/**"
		}
            	steps{
	    		echo 'Packaging worker app'
                        dir('worker'){
                                 sh 'mvn package -DskipTests'
				 archiveArtifacts artifacts: '**/target/*.jar'
                        }
	    	} 
	}
    }
    
    post{
        always{
            echo "Building multibranch pipeline for worker is completed.."
        }
    }
}
